const BAD_REQUEST_ERROR_CODE = 400;
const UNAUTHORIZED = 401;
const FORBIDDEN = 403;
const NOT_FOUND_ERROR_CODE = 404;
const CONFLICT_ERROR_CODE = 409;
const SERVER_ERROR_CODE = 500;

const SUCCESS_CODE = 200;
const SUCCESS_CREATED_CODE = 201;

module.exports = {
	BAD_REQUEST_ERROR_CODE,
	UNAUTHORIZED,
	FORBIDDEN,
	NOT_FOUND_ERROR_CODE,
	CONFLICT_ERROR_CODE,
	SERVER_ERROR_CODE,
	SUCCESS_CODE,
	SUCCESS_CREATED_CODE,
};
